// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheet.Infrastructure.Persistence;

#nullable disable

namespace TimeSheet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222064849_AddEmployerAttendanceRecords")]
    partial class AddEmployerAttendanceRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.EmployerAttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WorkingHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_EmployerAttendanceRecords_UserId_Date");

                    b.ToTable("EmployerAttendanceRecords", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.EmployerImportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDaysProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_EmployerImportLogs_UserId");

                    b.ToTable("EmployerImportLogs", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Holidays_UserId");

                    b.HasIndex("UserId", "StartDate")
                        .HasDatabaseName("IX_Holidays_UserId_StartDate");

                    b.HasIndex("UserId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_Holidays_UserId_DateRange");

                    b.ToTable("Holidays", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.PendingMnemonic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Mnemonic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_PendingMnemonics_ExpiresAt");

                    b.HasIndex("Mnemonic")
                        .IsUnique()
                        .HasDatabaseName("IX_PendingMnemonics_Mnemonic");

                    b.ToTable("PendingMnemonics", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.TrackingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommuteDirection")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_TrackingSessions_StartedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TrackingSessions_UserId");

                    b.HasIndex("UserId", "EndedAt")
                        .HasDatabaseName("IX_TrackingSessions_UserId_EndedAt");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("IX_TrackingSessions_UserId_StartedAt");

                    b.ToTable("TrackingSessions", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForgotShutdownThresholdPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LunchReminderHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LunchReminderMinute")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxCommuteHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxLunchHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxWorkHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetOfficeHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetWorkHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UtcOffsetMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_TelegramUserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.UserComplianceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClockInDefinition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClockOutDefinition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("FixedClockIn")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("FixedClockOut")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("ThresholdHours")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RuleType")
                        .IsUnique()
                        .HasDatabaseName("IX_UserComplianceRules_UserId_RuleType");

                    b.ToTable("UserComplianceRules", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.EmployerAttendanceRecord", b =>
                {
                    b.HasOne("TimeSheet.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.EmployerImportLog", b =>
                {
                    b.HasOne("TimeSheet.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.UserComplianceRule", b =>
                {
                    b.HasOne("TimeSheet.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
