using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="EmployerImportLog"/> entity.
/// </summary>
internal sealed class EmployerImportLogConfiguration : IEntityTypeConfiguration<EmployerImportLog>
{
    public void Configure(EntityTypeBuilder<EmployerImportLog> builder)
    {
        // Table name
        builder.ToTable("EmployerImportLogs");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.UserId)
            .IsRequired();

        builder.Property(e => e.RecordsImported)
            .IsRequired();

        builder.Property(e => e.RecordsSkipped)
            .IsRequired();

        builder.Property(e => e.TotalDaysProcessed)
            .IsRequired();

        // Index on UserId for efficient lookup of import history per user
        builder.HasIndex(e => e.UserId)
            .HasDatabaseName("IX_EmployerImportLogs_UserId");

        // Foreign key relationship to Users table
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(e => e.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
