using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="EmployerAttendanceRecord"/> entity.
/// </summary>
internal sealed class EmployerAttendanceRecordConfiguration : IEntityTypeConfiguration<EmployerAttendanceRecord>
{
    public void Configure(EntityTypeBuilder<EmployerAttendanceRecord> builder)
    {
        // Table name
        builder.ToTable("EmployerAttendanceRecords");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.UserId)
            .IsRequired();

        builder.Property(e => e.Date)
            .IsRequired();

        builder.Property(e => e.ClockIn)
            .IsRequired(false);

        builder.Property(e => e.ClockOut)
            .IsRequired(false);

        builder.Property(e => e.WorkingHours)
            .IsRequired(false);

        builder.Property(e => e.HasConflict)
            .IsRequired();

        builder.Property(e => e.ConflictType)
            .IsRequired(false)
            .HasMaxLength(100);

        builder.Property(e => e.EventTypes)
            .IsRequired()
            .HasMaxLength(500);

        builder.Property(e => e.ImportBatchId)
            .IsRequired()
            .HasMaxLength(36); // GUID string length

        // Unique index on (UserId, Date) — enables idempotent upsert
        builder.HasIndex(e => new { e.UserId, e.Date })
            .IsUnique()
            .HasDatabaseName("IX_EmployerAttendanceRecords_UserId_Date");

        // Foreign key relationship to Users table
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(e => e.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
