using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="Holiday"/> entity.
/// </summary>
internal sealed class HolidayConfiguration : IEntityTypeConfiguration<Holiday>
{
    public void Configure(EntityTypeBuilder<Holiday> builder)
    {
        // Table name
        builder.ToTable("Holidays");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.UserId)
            .IsRequired();

        builder.Property(e => e.StartDate)
            .IsRequired();

        builder.Property(e => e.EndDate)
            .IsRequired();

        builder.Property(e => e.Type)
            .IsRequired()
            .HasConversion<string>(); // Store as string for readability

        builder.Property(e => e.Description)
            .IsRequired(false) // Nullable
            .HasMaxLength(500);

        // Indexes for common queries
        builder.HasIndex(e => e.UserId)
            .HasDatabaseName("IX_Holidays_UserId");

        builder.HasIndex(e => new { e.UserId, e.StartDate })
            .HasDatabaseName("IX_Holidays_UserId_StartDate");

        // Index for date range queries
        builder.HasIndex(e => new { e.UserId, e.StartDate, e.EndDate })
            .HasDatabaseName("IX_Holidays_UserId_DateRange");

        // Ignore computed properties
        builder.Ignore(e => e.IsSingleDay);
        builder.Ignore(e => e.DayCount);
    }
}
