using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="PendingMnemonic"/> entity.
/// </summary>
internal sealed class PendingMnemonicConfiguration : IEntityTypeConfiguration<PendingMnemonic>
{
    public void Configure(EntityTypeBuilder<PendingMnemonic> builder)
    {
        // Table name
        builder.ToTable("PendingMnemonics");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.Mnemonic)
            .IsRequired()
            .HasMaxLength(500); // BIP39 24-word mnemonic is ~250 chars, allow headroom

        builder.Property(e => e.ExpiresAt)
            .IsRequired();

        builder.Property(e => e.IsConsumed)
            .IsRequired()
            .HasDefaultValue(false);

        // Index on Mnemonic for fast lookup (unique since we don't want duplicates)
        builder.HasIndex(e => e.Mnemonic)
            .IsUnique()
            .HasDatabaseName("IX_PendingMnemonics_Mnemonic");

        // Index on ExpiresAt for efficient cleanup queries
        builder.HasIndex(e => e.ExpiresAt)
            .HasDatabaseName("IX_PendingMnemonics_ExpiresAt");
    }
}
