using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;
using TimeSheet.Core.Domain.Enums;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="TimeEntry"/> entity.
/// </summary>
internal sealed class TimeEntryConfiguration : IEntityTypeConfiguration<TimeEntry>
{
    public void Configure(EntityTypeBuilder<TimeEntry> builder)
    {
        // Table name
        builder.ToTable("TimeEntries");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.UserId)
            .IsRequired();

        builder.Property(e => e.State)
            .IsRequired()
            .HasConversion<string>(); // Store as string for readability

        builder.Property(e => e.StartedAt)
            .IsRequired();

        builder.Property(e => e.EndedAt)
            .IsRequired(false); // Nullable - null means active

        builder.Property(e => e.CommuteDirection)
            .IsRequired(false) // Nullable - only set for Commuting state
            .HasConversion<string>(); // Store as string for readability

        // Indexes for common queries
        builder.HasIndex(e => e.UserId)
            .HasDatabaseName("IX_TimeEntries_UserId");

        builder.HasIndex(e => e.StartedAt)
            .HasDatabaseName("IX_TimeEntries_StartedAt");

        builder.HasIndex(e => new { e.UserId, e.StartedAt })
            .HasDatabaseName("IX_TimeEntries_UserId_StartedAt");

        // Ignore computed properties
        builder.Ignore(e => e.IsActive);
    }
}
