using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="User"/> entity.
/// </summary>
internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        // Table name
        builder.ToTable("Users");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.TelegramUserId)
            .IsRequired();

        builder.Property(e => e.TelegramUsername)
            .IsRequired(false) // Nullable
            .HasMaxLength(255);

        builder.Property(e => e.IsAdmin)
            .IsRequired();

        builder.Property(e => e.UtcOffsetMinutes)
            .IsRequired()
            .HasDefaultValue(0);

        builder.Property(e => e.RegisteredAt)
            .IsRequired();

        // Unique index on TelegramUserId
        builder.HasIndex(e => e.TelegramUserId)
            .IsUnique()
            .HasDatabaseName("IX_Users_TelegramUserId");
    }
}
