using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeSheet.Core.Domain.Entities;

namespace TimeSheet.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="UserComplianceRule"/> entity.
/// </summary>
internal sealed class UserComplianceRuleConfiguration : IEntityTypeConfiguration<UserComplianceRule>
{
    public void Configure(EntityTypeBuilder<UserComplianceRule> builder)
    {
        // Table name
        builder.ToTable("UserComplianceRules");

        // Primary key
        builder.HasKey(e => e.Id);

        // Properties
        builder.Property(e => e.Id)
            .IsRequired()
            .ValueGeneratedNever(); // Generated by BaseEntity constructor

        builder.Property(e => e.CreatedAt)
            .IsRequired();

        builder.Property(e => e.UserId)
            .IsRequired();

        builder.Property(e => e.RuleType)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(e => e.IsEnabled)
            .IsRequired()
            .HasDefaultValue(true);

        builder.Property(e => e.ThresholdHours)
            .IsRequired();

        builder.Property(e => e.ClockInDefinition)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(e => e.ClockOutDefinition)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(e => e.FixedClockIn)
            .IsRequired(false); // Nullable

        builder.Property(e => e.FixedClockOut)
            .IsRequired(false); // Nullable

        // Unique index: one rule per user per rule type
        builder.HasIndex(e => new { e.UserId, e.RuleType })
            .IsUnique()
            .HasDatabaseName("IX_UserComplianceRules_UserId_RuleType");

        // Foreign key relationship to Users table
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(e => e.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
