// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheet.Infrastructure.Persistence;

#nullable disable

namespace TimeSheet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TimeSheetDbContext))]
    [Migration("20260125124133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtcOffsetHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.WorkDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.User", b =>
                {
                    b.OwnsMany("TimeSheet.Core.Domain.ValueObjects.ExternalIdentity", "Identities", b1 =>
                        {
                            b1.Property<int>("InternalId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<long>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("IdentityProvider")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("InternalId");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserIdentities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("TimeSheet.Core.Domain.ValueObjects.NotificationPreferences", "NotificationPreferences", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("ClockOutReminderEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EndOfDayReminderEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("EndOfDayReminderTime")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("GoalAchievedNotificationEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("LunchReminderEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("LunchReminderTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Identities");

                    b.Navigation("NotificationPreferences")
                        .IsRequired();
                });

            modelBuilder.Entity("TimeSheet.Core.Domain.Entities.WorkDay", b =>
                {
                    b.OwnsMany("TimeSheet.Core.Domain.Entities.StateTransition", "_transitions", b1 =>
                        {
                            b1.Property<int>("InternalId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FromState")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ToState")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("WorkDayId")
                                .HasColumnType("TEXT");

                            b1.HasKey("InternalId");

                            b1.HasIndex("WorkDayId");

                            b1.ToTable("StateTransitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkDayId");
                        });

                    b.Navigation("_transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
